In [1]:
import numpy as np
from lib.fsfb import FSFB
from control import lqr, dlqr

A = np.array([
    [0,1],
    [0,-0.2]
])
B = np.array([
    [0],
    [1]
])
C = np.array([[0], [1]])
D = np.array([[0], [0]])

Q = np.array([
    [1, 0],
    [0, 1]
])
R = np.array([
    [1]
])

In [2]:
fsfb = FSFB(A,B,C,D,0.1)
fsfb.lqr(Q, R)
fsfb.K

array([[1.        , 1.54355958]])

In [3]:
lqr(fsfb.A, fsfb.B, fsfb.Q, fsfb.R)[0]

array([[1.        , 1.54355958]])

In [4]:
fsfb.Kd

array([[1.08019513, 1.63076311]])

In [5]:
dlqr(fsfb.Ad, fsfb.Bd, fsfb.Q, fsfb.R)[0]

array([[0.92575867, 1.46159314]])