In [236]:
from casadi import * #type: ignore

x = MX.sym("x") #type: ignore
print("x:", x)

x: x


In [237]:
y = SX.sym("y", 5) #type: ignore
Z = SX.sym("Z", 4, 2) #type: ignore
print("y_", y)
print("Z:", Z)

y_ [y_0, y_1, y_2, y_3, y_4]
Z: 
[[Z_0, Z_4], 
 [Z_1, Z_5], 
 [Z_2, Z_6], 
 [Z_3, Z_7]]


In [238]:
f = x**2 + 10
f = sqrt(f)
print("f:", f)

f: sqrt((10+sq(x)))


In [239]:
B1 = SX.zeros(4,5) #type: ignore
B2 = SX(4,5) #type: ignore
B4 = SX.eye(4) #type: ignore
print("B1:", B1)
print("B2:", B2)
print("B4:", B4)

B1: @1=0, 
[[@1, @1, @1, @1, @1], 
 [@1, @1, @1, @1, @1], 
 [@1, @1, @1, @1, @1], 
 [@1, @1, @1, @1, @1]]
B2: 
[[00, 00, 00, 00, 00], 
 [00, 00, 00, 00, 00], 
 [00, 00, 00, 00, 00], 
 [00, 00, 00, 00, 00]]
B4: @1=1, 
[[@1, 00, 00, 00], 
 [00, @1, 00, 00], 
 [00, 00, @1, 00], 
 [00, 00, 00, @1]]


In [240]:
import numpy as np
from scipy.sparse import csc_matrix #type: ignore

C = DM(2,3)
C[1,1] = 4
C[0,1] = 5
C_dense = C.full()
C_dense_np = np.array(C)
print("C_dense:")
print(C_dense)
print("C_dense np:")
print(C_dense_np)

C_sparse = C.sparse()
C_sparse_csc = csc_matrix(C)
print("C_sparse:")
print(C_sparse)
print("C_sparse csc:")
print(C_sparse_csc)

C_dense:
[[0. 5. 0.]
 [0. 4. 0.]]
C_dense np:
[[0. 5. 0.]
 [0. 4. 0.]]
C_sparse:
  (0, 1)	5.0
  (1, 1)	4.0
C_sparse csc:
  (0, 1)	5.0
  (1, 1)	4.0


In [241]:
x = SX.sym("x",2,2) #type: ignore
y = SX.sym("y") #type: ignore
f = 3*x + y
print("f:", f)
print("f.shape:", f.shape)

f: @1=3, 
[[((@1*x_0)+y), ((@1*x_2)+y)], 
 [((@1*x_1)+y), ((@1*x_3)+y)]]
f.shape: (2, 2)


In [242]:
x = MX.sym("x",2,2) #type: ignore
y = MX.sym("y") #type: ignore
f = 3*x + y
print("f:", f)
print("f.shape:", f.shape)

f: ((3*x)+y)
f.shape: (2, 2)


In [243]:
print(x[0,0])

x[0]


In [244]:
x = MX.sym("x", 2) #type: ignore
A = MX(2,2)
A[0,0] = x[0]
A[1,1] = x[0] + x[1]
print("A:", A)

A: (project((zeros(2x2,1nz)[0] = x[0]))[1] = (x[0]+x[1]))


In [245]:
print(SX.sym("x", Sparsity.lower(3))) #type: ignore


[[x_0, 00, 00], 
 [x_1, x_3, 00], 
 [x_2, x_4, x_5]]


In [246]:
M = SX([[3,7],[4,5]])
print("M[0,:]:", M[0,:])
M[0,:] = 1
print(M)

M[0,:]: [[3, 7]]
@1=1, 
[[@1, @1], 
 [4, 5]]


In [247]:
x = SX.sym("x")
y = SX.sym("y",2,2)
print(sin(y)-x)


[[(sin(y_0)-x), (sin(y_2)-x)], 
 [(sin(y_1)-x), (sin(y_3)-x)]]


In [248]:
print(y*y, y@y)


[[sq(y_0), sq(y_2)], 
 [sq(y_1), sq(y_3)]] 
[[(sq(y_0)+(y_2*y_1)), ((y_0*y_2)+(y_2*y_3))], 
 [((y_1*y_0)+(y_3*y_1)), ((y_1*y_2)+sq(y_3))]]


In [249]:
print(y)
print(y.T)


[[y_0, y_2], 
 [y_1, y_3]]

[[y_0, y_1], 
 [y_2, y_3]]


In [250]:
x = SX.eye(4)
print(reshape(x,2,8))

@1=1, 
[[@1, 00, 00, 00, 00, @1, 00, 00], 
 [00, 00, @1, 00, 00, 00, 00, @1]]


In [251]:
x = SX.sym("x",5)
y = SX.sym("y",5)
print(vertcat(x,y))
print(horzcat(x,y))

[x_0, x_1, x_2, x_3, x_4, y_0, y_1, y_2, y_3, y_4]

[[x_0, y_0], 
 [x_1, y_1], 
 [x_2, y_2], 
 [x_3, y_3], 
 [x_4, y_4]]


In [252]:
L = [x,y]
print(hcat(L),vcat(L))


[[x_0, y_0], 
 [x_1, y_1], 
 [x_2, y_2], 
 [x_3, y_3], 
 [x_4, y_4]] [x_0, x_1, x_2, x_3, x_4, y_0, y_1, y_2, y_3, y_4]


In [253]:
x = SX.sym("x",5,2)
w = horzsplit(x,[0,1,2])
print(w)

# splitting with horzplit and vertsplit is equivalent with slicing for SX but way more efficient for MX

[SX([x_0, x_1, x_2, x_3, x_4]), SX([x_5, x_6, x_7, x_8, x_9])]


In [254]:
x = SX.sym("x",2,2)
print(dot(x,x))

(((sq(x_0)+sq(x_1))+sq(x_2))+sq(x_3))


In [255]:
A = MX.sym("A",3,3)
b = MX.sym("b",3)
print(solve(A,b))

(A\b)


In [256]:
A = SX.sym("A",3,2)
x = SX.sym("x",2)
print(jacobian(A@x,x))


[[A_0, A_3], 
 [A_1, A_4], 
 [A_2, A_5]]


In [257]:
print(gradient(dot(A,A),A))


[[(A_0+A_0), (A_3+A_3)], 
 [(A_1+A_1), (A_4+A_4)], 
 [(A_2+A_2), (A_5+A_5)]]


In [258]:
[H,g] = hessian(dot(x,x),x)
print("H:",H)

H: @1=2, 
[[@1, 00], 
 [00, @1]]


In [259]:
A = DM([[1,3],[4,7],[2,8]])
x = SX.sym("x",2)
v = SX.sym("v",2)
f = mtimes(A,x)
print(jtimes(f,x,v))

[(v_0+(3*v_1)), ((4*v_0)+(7*v_1)), ((2*v_0)+(8*v_1))]


In [260]:
w = SX.sym("w",3)
f = mtimes(A,x)
print(jtimes(f,x,w,True))

[(((2*w_2)+(4*w_1))+w_0), (((8*w_2)+(7*w_1))+(3*w_0))]


In [261]:
x = SX.sym("x", 2)
y = SX.sym("y")
f = Function("f",[x,y],[x,sin(y)*x])
print("f:",f)

f: f:(i0[2],i1)->(o0[2],o1[2]) SXFunction


In [262]:
x = MX.sym("x",2)
y = MX.sym("y")
f = Function("f",[x,y],[x,sin(y)*x])
print("f:", f)

f: f:(i0[2],i1)->(o0[2],o1[2]) MXFunction


In [263]:
x = MX.sym("x",2)
y = MX.sym("y")
f = Function("f",[x,y],[x,sin(y)*x],["x","y"],["r","q"])
print("f:", f)

f: f:(x[2],y)->(r[2],q[2]) MXFunction


In [264]:
r0, q0 = f(1.1,3.3)
print("r0:", r0)
print("q0:", q0)

r0: [1.1, 1.1]
q0: [-0.17352, -0.17352]


In [265]:
res = f(x=1.1,y=3.3)
res

{'q': DM([-0.17352, -0.17352]), 'r': DM([1.1, 1.1])}

In [266]:
arg = [1.1,3.3]
res = f.call(arg)
print("res:", res)
arg = {"x":1.1,"y":3.3}
res = f.call(arg)
print("res:", res)

res: [DM([1.1, 1.1]), DM([-0.17352, -0.17352])]
res: {'q': DM([-0.17352, -0.17352]), 'r': DM([1.1, 1.1])}


In [267]:
mx_function = f
sx_function = mx_function.expand()
print(f)
print(sx_function)

f:(x[2],y)->(r[2],q[2]) MXFunction
f:(x[2],y)->(r[2],q[2]) SXFunction


In [268]:
nz = 2
nx = 2
z = SX.sym("x",nz)
x = SX.sym("x",nx)
g0 = sin(x+z)
g1 = cos(x-z)
g = Function("g",[z,x],[g0,g1])
G = rootfinder("G", "newton", g)
print(G)

G:(i0[2],i1[2])->(o0[2],o1[2]) Newton


In [269]:
x = SX.sym("x")
z = SX.sym("z")
p = SX.sym("p")
dae = {"x":x, "z":z, "p":p, "ode":z+p, "alg":z*cos(z)-x}
F = integrator("F", "idas", dae, {"t0":0, "tf":1})
print("F:",F)

F: F:(x0,z0,p,u[0],adj_xf[],adj_zf[],adj_qf[])->(xf,zf,qf[0],adj_x0[],adj_z0[],adj_p[],adj_u[]) IdasInterface


CasADi - 2023-06-25 16:38:06 WARNING("The options 't0', 'tf', 'grid' and 'output_t0' have been deprecated. Set the time grid by proving additional argument to the 'integrator' call instead.") [.../casadi/core/integrator.cpp:495]


In [270]:
r = F(x0=0,z0=0,p=0.1)
print(r["xf"])

0.1724


In [272]:
x = SX.sym("x")
y = SX.sym("y")
z = SX.sym("z")
nlp = {"x": vertcat(x,y,z), "f": x**2+100*z**2, "g": z+(1-x)**2-y}
S = nlpsol("S", "ipopt", nlp)
print(S)

S:(x0[3],p[],lbx[3],ubx[3],lbg,ubg,lam_x0[3],lam_g0)->(x[3],f,g,lam_x[3],lam_g,lam_p[]) IpoptInterface


In [279]:
r = S(x0=[2.5,3.0,0.75],\
      lbg=0, ubg=0)
x_opt = r["x"]  

This is Ipopt version 3.14.11, running with linear solver MUMPS 5.4.1.

Number of nonzeros in equality constraint Jacobian...:        3
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        2

Total number of variables............................:        3
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        1
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  6.2500000e+01 0.00e+00 9.00e+01  -1.0 0.00e+00    -  0.00e+00 0.00e+00 